/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface OapVersions {
        "version": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLOapVersionsElement extends Components.OapVersions, HTMLStencilElement {
    }
    var HTMLOapVersionsElement: {
        prototype: HTMLOapVersionsElement;
        new (): HTMLOapVersionsElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "oap-versions": HTMLOapVersionsElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface OapVersions {
        "onOapClose"?: (event: CustomEvent<void>) => void;
        "version"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "oap-versions": OapVersions;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "oap-versions": LocalJSX.OapVersions & JSXBase.HTMLAttributes<HTMLOapVersionsElement>;
        }
    }
}
